for _ in range(int(input())):
	n=int(input())
	a=list(map(int,input().split()))
	s=0
	i=0
	j=n-1
	while(i!=j):
		if(a[i]<a[j]):
			if(a[i+1]<=a[i]):
				s+=a[i]-a[i+1]+1
				a[i+1]=a[i]+1
			i+=1
		elif(a[i]>a[j]):
			if(a[j-1]<=a[j]):
				s+=a[j]-a[j-1]+1
				a[j-1]=a[j]+1
			j-=1
		else:
			if(a[i+1]>a[i]):
				i+=1
			elif(a[j-1]>a[j]):
				j-=1
			else:
				if((a[i]-a[i+1])<(a[j]-a[j-1])):
					s+=a[i]-a[i+1]+1
					a[i+1]=a[i]+1
					i+=1
				else:
					s+=a[j]-a[j-1]+1
					a[j-1]=a[j]+1
					j-=1
	print(s)